services:
  api:
    container_name: pecas-api-dev
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.dev

  db:
    container_name: pecas-db-dev
    image: postgres:17-alpine
    volumes:
      - pecas_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: pecasdb
      POSTGRES_USER: userpecas
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: pecas-redis
    ports:
      - "6379:6379"
    volumes:
      - pecas_redis_data:/data

  celery:
    build: .
    container_name: pecas-celery-worker
    command: celery -A api worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
    env_file:
      - ./.env.dev

volumes:
  pecas_postgres_data:
  pecas_redis_data:
