# Generated by Django 5.1.6 on 2025-02-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name']},
        ),
    ]
