# Generated by Django 5.1.6 on 2025-02-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_carmodel_options_alter_part_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='car_models', to='api.part'),
        ),
    ]
